### ISSUE TITLE
libquazip error

### ISSUE THREAD

**Issue by jakewelde** [iq-motion-control/iq-control-center#12]
Hi folks,

After updating to the most recent version of the control center (on Ubuntu 22.04), I'm getting the following error when I try to run the app:

> ./AppRun: error while loading shared libraries: libquazip.so.1: cannot open shared object file: No such file or directory

I've run previous versions of the control center for years without issues, so not sure what could be causing this. Any advice you can give is much appreciated, thanks!

Best,
Jake

**Comment by jakewelde** [comment]
Small update: it seems like maybe the breaking change is actually in v1.5.1, because I had to downgrade to v1.5.0 to resolve this. Thanks!

**Comment by iq-fred** [comment]
Hi Jake, I've added this bug to the team's backlog to try and replicate and identify the issue, we'll let you know what we find out.

**Comment by vertiq-jordan** [comment]
Hello Jake! We've found the issue, and will release a patch soon. Thank you for reporting!

**Comment by jakewelde** [comment]
Fantastic, thanks! :smile:

**Comment by iq-fred** [comment]
@jakewelde We believe that the issue should be resolved in our latest v1.5.3 version, let us know if you still see the problem

**Comment by jakewelde** [comment]
Solved, thank you very much!
