### ISSUE TITLE
Pre-built linux binaries

### ISSUE THREAD

**Issue by timonsku** [iq-motion-control/iq-control-center#2]
Would be great if you could also offer a Linux build with each release.
It seems to run just fine on Linux, compiling it with the laterst QTCreator on Ubuntu. Couldn't test it with an actual motor so far though.

An appimage distribution is probably the most user friendly. Tools like https://github.com/probonopd/linuxdeployqt or https://github.com/linuxdeploy/linuxdeploy are very easy to use.

**Comment by IQ-raf** [comment]
Hi !
Thanks a lot for your input. The App was developed using Linux (Ubuntu) so you are right it has been tested and will compile using the QTCreator on Ubuntu.  Make sure to have the Resource folder in the same directory as your executable (otherwise the tabs won't populate when you connect a motor). I will add this to the README.

We are currently working on a full Linux build and it will probably come with v1.0.0 along with an automatic updater. This should be released in a week or two so stay tuned !

**Comment by timonsku** [comment]
Awesome!

**Comment by 222464** [comment]
Hi, I am trying to compile this on Arch Linux (Manjaro), but I get:

> Project ERROR: Unknown module(s) in QT: autoupdatergui

I tried installing it from AUR, from source, from binaries, but it seems completely broken (cannot find std::optional, cannot find maintenance tool). The headers also reference files that look like they are part of the library, but are not.

Any ideas? Will try using a VM for now, if that works.

**Comment by IQ-raf** [comment]
Hey, yes this is normal, we are using version 2.1.5 for the Auto updater library, here is the [tag link](https://github.com/Skycoder42/QtAutoUpdater/releases/tag/2.1.5-4). Unfortunately, the latest versions of that library are not backward compatible, I recommend clicking on the link and following the instructions at that commit.

Let me know if this works

**Comment by 222464** [comment]
Hi,

Thanks for response. With that version I was indeed able to compile it, thanks!

**Comment by IQ-raf** [comment]
Great! I am leaving this issue open until we make real Linux binaries

**Comment by IQ-Malik** [comment]
Wanted to update the progress on this. We have successfully created Linux distributions and need to add support for our upcoming Vertiq8108 Motors. Once this is achieved, we will push a public version and this issue will be closed. Until them, I am able to help anyone through any issues they may be having with compiling for Linux.

**Comment by IQ-Malik** [comment]
You can find the Linux Binaries [here](https://github.com/iq-motion-control/iq-control-center/releases/tag/v1.2.0)

**Comment by jakewelde** [comment]
Hi folks! Just curious, would you perhaps consider providing ARM64 binaries? It would be particularly convenient to be able to run the control center on my embedded ARM device running Ubuntu. This is what my motors are connected to at deployment, and it would be helpful to be able to run "in-place" firmware updates, etc. But, the binaries are provided only for x86. Just wanted to mention interest in this feature if it became an option! Thanks.

**Comment by Vertiq-Ben** [comment]
Hi @jakewelde thank you for your inquiry! Unfortunately we are not planning on building on the ARM64 architecture anytime soon. Have you tried using our API's? For example, if you're using a raspberry pi you can use our [python API](https://pypi.org/project/iqmotion/) to configure your module. There are examples on how to do this in our documentation: https://iqmotion.readthedocs.io/en/latest/api_docs/python.html
